### ISSUE TITLE
Is this compatible with the 1401 ?

### ISSUE THREAD

**Issue by psxpetey** [ffxx68/sharp-pc-software#1]
I have a 1401 nowhere else really to ask this question. A how is it loaded in the calculator and b is it compatible with the 1401 especially petools

**Comment by ffxx68** [comment]
Hi ,  to load onto calculator you need some software on a Windows PC. See this: https://www.peil-partner.de/ifhe.de/sharp/
And I'm afraid no, as petools was written for the 1403(H), which might have different ROM or display addresses. You might give it a try. Maybe some of the calls still work on 1401 too...
